redDisk = [
"46 64 4 1",
"  c #030000",
". c #550000",
"X c #F50000",
"o c None",
"oooooooooooooo             o  o oo  oooo   ooo",
"ooooooooo                            ooo    oo",
"oooooo                                      oo",
"oooo         ....X.XXXXXXXX.X...            oo",
"oo      ...XXXXXXXXXXXXXXXXXXXXXXXX...      oo",
"o     .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.     o",
"   ..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.    ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.   ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.   ",
"     .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.     ",
"       .XXXXXXXXXXXXXXXXXXXXXXXXXXXXX..       ",
"           ...XXXXXXXXXXXXXXXXXXX..           ",
"   XX              ....... .            ..X   ",
"   XXXX..                            ..XXXX   ",
"   XXXXXXXX...                  ...XXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXX..X.X.XXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..   ",
"    . .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.      ",
"        ...XXXXXXXXXXXXXXXXXXXXXXXX...        ",
"              .....X.XXXX.X.X...              ",
"   ..           .                        ..   ",
"   XXX.                                .XXX   ",
"   XXXXXXX..   . .                ...XXXXXX   ",
"   XXXXXXXXXXXX....... ......X.XXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.   ",
"     .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.     ",
"       ..XXXXXXXXXXXXXXXXXXXXXXXXXXXX.        ",
"           ....XXXXXXXXXXXXXXX.X..            ",
"   .                  .                   .   ",
"   XX.                                  .XX   ",
"   XXXXX..                          ..XXXXX   ",
"   XXXXXXXXXX....           . ...XXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.   ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.    ",
"       .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..      ",
"       . ....XXXXXXXXXXXXXXXXXXXX...          ",
"    .           . .....X.....                 ",
"   X.                .                  ..X   ",
"   XXXX.                              .XXXX   ",
"   XXXXXXXX..                    ..XXXXXXXX   ",
"   XXXXXXXXXXXXXXX.XX....XX.XXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"o   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   o",
"o     .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.     o",
"oo      ..XXXXXXXXXXXXXXXXXXXXXXXXX...      oo",
"oo o         ....X.XXXXXXX.X.X...         oooo",
"oooooo                            oo    oooooo",
"oooooooooo                              oooooo",
"oooooooooo       o o      o o oo o      oooooo"
]


yellowDisk = [
"46 64 4 1",
"  c #030201",
". c #554820",
"X c #FABE00",
"o c None",
"                                              ",
"                                              ",
"                   .                          ",
"             ...o.oooooooooo.o.o.             ",
"        ..oooooooooooooooooooooooooo..        ",
"      ooooooooooooooooooooooooooooooooo.      ",
"    .ooooooooooooooooooooooooooooooooooooo    ",
"   oooooooooooooooooooooooooooooooooooooooo   ",
"   .oooooooooooooooooooooooooooooooooooooo..  ",
"    .oooooooooooooooooooooooooooooooooooo     ",
"       .oooooooooooooooooooooooooooooo.       ",
"        . ..oooooooooooooooooooooo..          ",
"   oo. .          ..........            .oo.  ",
"  .oooo..               .          . .ooooo   ",
"   oooooooooo.              .  ..oooooooooo   ",
"   oooooooooooooooooooo.ooooooooooooooooooo.  ",
"   oooooooooooooooooooooooooooooooooooooooo   ",
"  .oooooooooooooooooooooooooooooooooooooooo   ",
"   oooooooooooooooooooooooooooooooooooooooo   ",
"   oooooooooooooooooooooooooooooooooooooooo   ",
"    oooooooooooooooooooooooooooooooooooooo    ",
"     .oooooooooooooooooooooooooooooooooo.     ",
"        ..oooooooooooooooooooooooooo..        ",
"            ....ooooooooooo.oo...             ",
"   ..                                    ..   ",
"   XXX.                                .XXX   ",
"   XXXXXXX..                      ...XXXXXX   ",
"   XXXXXXXXXXX.XX.... .......X.XXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.   ",
"     .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.     ",
"       ..XXXXXXXXXXXXXXXXXXXXXXXXXXXX..       ",
"           ....XXXXXXXXXXXXXXX.X...           ",
"   .                  . .                 .   ",
"   XX.                                  .XX   ",
"   XXXXX..                          ..XXXXX   ",
"   XXXXXXXXXX....            ....XXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"  ..XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.   ",
"    .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.    ",
"       .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXX..      ",
"          ..XXXXXXXXXXXXXXXXXXXXX....         ",
"                .......X.....                 ",
"   X.                                    .X   ",
"   XXXX.                              .XXXX   ",
"   XXXXXXXX..                    ..XXXXXXXX   ",
"   XXXXXXXXXXXXXXX.X.X...X.XXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"   XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX   ",
"    XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX    ",
"      .XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX.      ",
"        ..XXXXXXXXXXXXXXXXXXXXXXXXXX..        ",
"             ....X.XXXXXXXX..X...             ",
"                                              ",
"                                              ",
"                                              "
]

greenDisk = [
"46 64 5 1",
" 	c None",
".	c #020302",
"+	c #2E572E",
"@	c #F5F5F5",
"#	c #29AB1B",
"..............................................",
"..............................................",
"..............................................",
".............++++@+@@@@@@@+@+@+++.............",
"........+++@@@@@@@@@@@@@@@@@@@@@@@+@++........",
"......+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+......",
"....+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+....",
"...@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@...",
"...+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+...",
".....+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+.....",
".......+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+.......",
"...........++@@@@@@@@@@@@@@@@@@@@++...........",
"...@@..............+++++++++............+@@...",
"...@@@@++..+........+................++@@@@...",
"...@@@@@@@@+++..................++@@@@@@@@@...",
"...@@@@@@@@@@@@@@@@+@@@+@+@@@@@@@@@@@@@@@@@...",
"...@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@...",
"...@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@...",
"...@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@...",
"...@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@...",
"....@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@....",
"......+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+......",
"........+++@@@@@@@@@@@@@@@@@@@@@@@@+++........",
".............+++@++@+@@@+@@+@++++.............",
"...@+....................................+@...",
"...@@@++..............................++@@@...",
"...@@@@@@@++............++........+++@@@@@@...",
"...@@@@@@@@@@@@@+@+++++++++++@+@@@@@@@@@@@@...",
"...@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@...",
"...@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@...",
"...@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@...",
"...@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@...",
"...+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+...",
".....+@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@+.....",
".......++@@@@@@@@@@@@@@@@@@@@@@@@@@@@++.......",
"...........++++@@@@@@@@@@@@@@@@@+++...........",
"....+.................+++.................+...",
"...###..................................###...",
"...######+.........................++######...",
"...##########++#..............+#+##########...",
"...########################################+..",
"...########################################...",
"...########################################+..",
"...########################################...",
"...+#######################################...",
"....######################################....",
"......#################################+......",
"..........#########################++.........",
".................++++++++++++.................",
"...##+...................................##...",
"...#####..............................#####...",
"...#########+......+...........+..#########...",
"...#####################+##################+..",
"...########################################...",
"...########################################+..",
"...########################################...",
"...########################################...",
"....######################################....",
"....+.+#################################......",
"........#############################++.......",
"............+++#+#+#########+#++..............",
"........................+.....................",
"..............................................",
".............................................."
]
